version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: /
    labels:
      - dependabot
      - maven
    schedule:
      interval: weekly
