name: Java gaming

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
       java-version: '11'
       distribution: 'adopt'
 
    - name: Build

    - run: mvn package
    - run: mkdir build && cp target/*.jar build
    - uses: actions/upload-artifact@v2
      with:
        name: pet-teleport
        path: build
        

