name: maven-release-ci

on:
  push:
    tags: [ v* ]
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package
    - name: Set variables
      id: vars
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        title: "PetTeleport ${{ steps.vars.outputs.version }"
        files: | 
            target/*.jar
