name: Build PetTeleport

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16

    - name: Build with Maven
      run: |
        chmod +x maven
        mvn package
    - name: Archive plugin jars on GitHub
      uses: actions/upload-artifact@master
      with:
        name: Plugin Jar
        path: jar/

        

