name: maven-preview-ci
on:
  push:
    branches: [ "dev/*" ]
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache local Maven repository   
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
           ${{ runner.os }}-maven-

    - name: Set pom version to release
      id: pom
      run: |
        mvn -B versions:set -DnewVersion=${{github.event.pull_request.title}}
        echo "JAR=$(mvn git-commit-id:revision -q -Dexec.executable=echo -Dexec.args="\${project.build.finalName}" --non-recursive exec:exec).jar >> $GITHUB_ENV"
        echo "VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_ENV"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub"
        git commit -m "Release ${{github.event.pull_request.title}}" -a

    - name: Build with Maven
      run: mvn package

    - name: Set Variables
      id: vars
      run: echo ::set-output name=version::${GITHUB_REF#refs/*\/dev/}
    
    - name: Automatic Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.vars.outputs.version }}-SNAPSHOT"
        prerelease: true
        title: "Development Build (${{ steps.vars.outputs.version }})"
        files: |
          target/(.jar|!(original-PetTeleport.jar))

    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.RELEASE_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '**New release for {{ EVENT_PAYLOAD.repository.full_name }}: Version ${{ steps.vars.outputs.version }}**```${{github.event.pull_request.body}}```Direct download: ${{steps.automatic_release.outputs.browser_download_url}}'