name: "Maven Release CI"

on:
  workflow_dispatch:
  push:
    tags: ["v*"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: "Build with Maven"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/*}

      - name: Publish Build Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ steps.vars.outputs.version }}"
          prerelease: false
          title: "PetTeleport ${{ steps.vars.outputs.version }}"
          files: |
            target/(.jar|!(original-PetTeleport*.jar))
